# Site settings
title: IT Kolledži LUG
email: 
description: > # this means to ignore newlines until "baseurl:"
  Eesti Infotehnoloogia Kolledži Linux User Group koduleht
baseurl: ""
url: "http://lug.itcollege.ee" # the base hostname & protocol for your site
github_username: EIK-LUG

# Build settings
markdown: kramdown

timezone: Europe/Tallinn
permalink: /:year/:month/:title

